// Declare variables and assign values
var firstName = "SWATI";
var lastName = "SHARMA";
var country = "india";
var city = "durgapur";
var age = 20;
var isMarried = false;
var year = 2023;

// Use typeof to check data types
console.log("firstName is a " + typeof firstName);
console.log("lastName is a " + typeof lastName);
console.log("country is a " + typeof country);
console.log("city is a " + typeof city);
console.log("age is a " + typeof age);
console.log("isMarried is a " + typeof isMarried);
console.log("year is a " + typeof year);