// Truthy Values:
var truthyValue1 = "Hello, World!";
var truthyValue2 = 42;
var truthyValue3 = { key: "value" };

// Falsy Values:
var falsyValue1 = "";
var falsyValue2 = 0;
var falsyValue3 = null;


if(truevalue1){
    console.log("truevalue1 is truthy");
}else{
    console.log("truevalue1 is falsy")
}

if (falsevalue2){
    console.log("falsevalue2 is truthy");
}else{
    console.log("falsevalue2 is falsy");
}